//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace net_mvc_day05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_data
    {
        public Nullable<System.DateTime> datatime { get; set; }
        public double Vall { get; set; }
        public byte[] State { get; set; }
        public byte[] I_pos { get; set; }
        public Nullable<double> I_System { get; set; }
        public string Switch { get; set; }
        public string Warning { get; set; }
        public Nullable<double> AHC_min { get; set; }
        public Nullable<double> SOC_min { get; set; }
        public Nullable<int> Charger_con { get; set; }
        public string Tag_Vmax { get; set; }
        public string Tag_Vmin { get; set; }
        public string Tag_Tmax { get; set; }
    }
}
