//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace net_mvc_day05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module_data1
    {
        public System.DateTime datatime { get; set; }
        public string Module_id { get; set; }
        public Nullable<double> V1 { get; set; }
        public Nullable<double> V2 { get; set; }
        public Nullable<double> V3 { get; set; }
        public Nullable<double> V4 { get; set; }
        public Nullable<double> V5 { get; set; }
        public Nullable<double> V6 { get; set; }
        public Nullable<double> V7 { get; set; }
        public Nullable<double> V8 { get; set; }
        public Nullable<double> T1 { get; set; }
        public Nullable<double> T2 { get; set; }
        public Nullable<double> T3 { get; set; }
        public Nullable<double> T4 { get; set; }
        public Nullable<double> T5 { get; set; }
        public Nullable<double> T6 { get; set; }
        public Nullable<double> T7 { get; set; }
        public Nullable<double> T8 { get; set; }
        public Nullable<double> SOC { get; set; }
        public Nullable<double> AHC { get; set; }
    }
}
