//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace net_mvc_day05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module_main_data
    {
        public System.DateTime datatime { get; set; }
        public string Module_id { get; set; }
        public double Vt { get; set; }
        public Nullable<double> Vmax { get; set; }
        public Nullable<double> Vmin { get; set; }
        public Nullable<double> Tmax { get; set; }
        public Nullable<double> SOC { get; set; }
        public Nullable<double> AHC { get; set; }
        public Nullable<double> Tag_Vmax { get; set; }
        public Nullable<double> Tag_Vmin { get; set; }
        public Nullable<double> Tag_Tmax { get; set; }
        public string I_Ba { get; set; }
        public string Ba_site { get; set; }
        public string BaF { get; set; }
        public string Warning { get; set; }
        public string Ba_sw { get; set; }
    }
}
